export const html = `<!doctype html>
<html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bom Flan — Mark Paid</title>
<style>
:root{font:16px system-ui;color:#35241b;background:#faf6ef}body{max-width:1040px;margin:auto;padding:24px}nav{display:flex;gap:10px;margin-bottom:28px}a{color:#66422b}nav a,nav strong{padding:10px 18px;border-radius:30px;border:1px solid #d8c8b6;text-decoration:none}nav strong{background:#40271c;color:white}h1{font-size:32px;margin:8px 0}p{color:#716357;line-height:1.6}.card{background:white;border:1px solid #e7ddcf;border-radius:18px;padding:24px;margin:20px 0}.fields{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}label{display:block;font-weight:600;margin:12px 0 6px}input,select,button{font:inherit;box-sizing:border-box;border-radius:9px;padding:12px;border:1px solid #d5c5b1}input:not([type=checkbox]){width:100%}button{cursor:pointer;background:#553321;color:white;font-weight:650}button:disabled{opacity:.45;cursor:not-allowed}.minor{background:#faf6ef;color:#553321}.actions{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin-top:16px}.notice{padding:12px;border-radius:9px;background:#fff0c7;color:#64430d}.status{white-space:pre-wrap;line-height:1.5}table{width:100%;border-collapse:collapse;font-size:14px}th,td{text-align:left;padding:12px 8px;border-bottom:1px solid #eee3d6;vertical-align:top}td small{display:block;color:#716357;margin-top:5px}.table{overflow:auto}.success{color:#137743}.failed{color:#b12e20}input[type=checkbox]{width:20px;height:20px;vertical-align:middle}#paid{min-width:160px}#ctwaWrap[hidden]{display:none}@media(max-width:680px){body{padding:14px}.fields{grid-template-columns:1fr}.card{padding:18px}h1{font-size:26px}}
</style></head><body><nav aria-label="Brand"><a href="/">Oflan</a><strong aria-current="page">Bom Flan</strong></nav>
<h1>Bom Flan Mark Paid</h1><p>Catat pembayaran yang sudah diterima. Riwayat dan nomor order khusus Bom Flan.</p>
<label for="mode">Mode</label><select id="mode"><option value="test">Test Events</option><option value="live">Order sungguhan</option></select>
<p class="notice" id="modeNote">Mode uji — terpisah dari order dan nomor urut produksi.</p><p id="setup" role="status"></p>
<section class="card"><h2>Mark Paid</h2><form id="form"><div class="fields"><div><label for="order">Order ID</label><input id="order" required maxlength="67" autocomplete="off"><button type="button" class="minor" id="generate">Buat nomor order</button></div><div><label for="phone">Phone</label><input id="phone" type="tel" required placeholder="08… atau +62…" autocomplete="off"></div><div><label for="value">Value (Rp)</label><input id="value" type="number" required min="1" max="1000000000" step="1" placeholder="109000"></div></div>
<div id="ctwaWrap" hidden><label for="ctwa">Click ID WhatsApp</label><input id="ctwa" autocomplete="off" maxlength="2048"><p>Gunakan ctwa_clid asli dari percakapan iklan WhatsApp.</p></div>
<label><input id="confirmed" type="checkbox" required> <span id="confirmText">Saya sedang menguji alur pembayaran.</span></label>
<div class="actions"><button id="paid" disabled>PAID</button></div></form><p class="status" id="message" role="status" aria-live="polite"></p></section>
<section class="card"><h2>History Today</h2><p>Hari ini berdasarkan Asia/Jakarta. SUCCESS berarti event diterima API Meta; tampilan Test Events diperiksa terpisah.</p><p id="summary">Memuat riwayat…</p><div class="actions"><button id="refresh" class="minor">Refresh</button><button id="resendAll" class="minor">Resend yang gagal hari ini</button></div><p id="historyError" role="alert"></p><div class="table"><table><thead><tr><th>Order / waktu</th><th>Phone</th><th>Value</th><th>Meta</th><th>Aksi</th></tr></thead><tbody id="rows"></tbody></table></div></section>
<script>
const $=id=>document.getElementById(id);let ready=false,busy=false,rows=[],generation=0;
const money=v=>'Rp '+new Intl.NumberFormat('id-ID').format(v);
function lock(v){busy=v;document.querySelectorAll('button,input,select').forEach(el=>el.disabled=v);$('paid').disabled=v||!ready;}
async function api(path,body){const mode=$('mode').value;const r=await fetch('/bom-flan/'+path+'?mode='+mode,{method:body?'POST':'GET',credentials:'same-origin',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(25000)});let d;try{d=await r.json();}catch{throw Error('Login atau koneksi terputus. Refresh halaman untuk masuk kembali.');}if(!r.ok)throw Error(d.message||'Permintaan gagal.');return d;}
async function history(){const g=generation;try{const d=await api('history-today');if(g!==generation)return;rows=d.orders;$('historyError').textContent='';$('summary').textContent=rows.length+' order · '+rows.filter(r=>r.status==='SUCCESS').length+' diterima Meta · '+rows.filter(r=>r.status==='FAILED').length+' gagal';$('rows').replaceChildren();for(const r of rows){const tr=document.createElement('tr');const values=[r.order_id,r.phone,money(r.value),r.status];for(const v of values){const td=document.createElement('td');td.textContent=v;tr.append(td);}const small=document.createElement('small');small.textContent=new Date(r.event_time*1000).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'});tr.children[0].append(small);tr.children[3].className=r.status==='SUCCESS'?'success':'failed';const detail=document.createElement('small');let result={};try{result=JSON.parse(r.result||'{}');}catch{}detail.textContent=result.message||('Percobaan: '+r.attempts+(result.code?' · Meta error '+result.code:''));tr.children[3].append(detail);const td=document.createElement('td');if(r.status!=='SUCCESS'){const b=document.createElement('button');b.textContent=r.status==='SENDING'?'Cek / lanjutkan':'Resend';b.className='minor';b.disabled=busy;b.onclick=()=>resend([r.order_id]);td.append(b);}tr.append(td);$('rows').append(tr);}if(!rows.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=5;td.textContent='Belum ada order pada mode ini hari ini.';tr.append(td);$('rows').append(tr);}}catch(e){if(g===generation){$('historyError').textContent=e.message;$('summary').textContent='Riwayat belum dapat dimuat.';}}}
async function setup(){generation++;rows=[];$('rows').replaceChildren();$('form').reset();ready=false;lock(true);const mode=$('mode').value;$('modeNote').textContent=mode==='test'?'Mode uji — terpisah dari order dan nomor urut produksi.':'Order sungguhan — tekan PAID hanya setelah uang diterima.';$('confirmText').textContent=mode==='test'?'Saya sedang menguji alur pembayaran.':'Saya sudah memeriksa bahwa pembayaran order ini benar-benar diterima.';$('message').textContent='';try{const c=await api('config');ready=c.ready;$('setup').textContent=c.ready?'Koneksi Bom Flan siap.':c.message;$('ctwaWrap').hidden=c.action_source!=='business_messaging';$('ctwa').required=c.action_source==='business_messaging';}catch(e){$('setup').textContent=e.message;}finally{lock(false);}await history();}
$('mode').onchange=setup;
$('generate').onclick=async()=>{lock(true);try{$('order').value=(await api('reserve-order-id',{})).order_id;}catch(e){$('message').textContent=e.message;}finally{lock(false);}};
$('form').onsubmit=async e=>{e.preventDefault();if(busy||!ready)return;lock(true);$('message').textContent='Menyimpan pembayaran…';try{const d=await api('mark-paid',{brand:'bomflan',order_id:$('order').value.trim(),phone:$('phone').value,value:Number($('value').value),paid_confirmed:$('confirmed').checked,ctwa_clid:$('ctwa').value.trim()});$('message').textContent=d.order_id+' — '+d.status+(d.status==='SUCCESS'?' · Purchase diterima Meta.':' · Periksa History dan gunakan resend untuk order ini.');if(d.status==='SUCCESS')$('form').reset();await history();}catch(err){$('message').textContent=err.message+' Periksa History sebelum mengulang. Gunakan Order ID yang sama.';await history();}finally{lock(false);}};
async function resend(ids){if(busy)return;lock(true);try{for(const id of ids){$('message').textContent='Mengirim ulang '+id;const d=await api('resend-meta',{order_id:id});$('message').textContent=id+' — '+d.status;}await history();}catch(e){$('message').textContent=e.message;await history();}finally{lock(false);}}
$('resendAll').onclick=()=>resend(rows.filter(r=>r.status==='FAILED').map(r=>r.order_id));$('refresh').onclick=history;
setup();setInterval(()=>{if(!busy)history();},15000);
</script></body></html>`;
